/**
 * PDF Compilation and Export Services
 */

function generateExpensePDF(requestingUser, fromDateStr, toDateStr, employeeFilter) {
  let tempSS = null;
  try {
    const reportDataRes = fetchExpenseReport(requestingUser, fromDateStr, toDateStr, employeeFilter);
    if (!reportDataRes.success) throw new Error(reportDataRes.message);

    const data = reportDataRes.data;
    if (!data || data.length === 0) throw new Error("No data available to generate a PDF.");

    tempSS = SpreadsheetApp.create(`Temp_Enterprise_Report_${Date.now()}`);
    const sheet = tempSS.getSheets()[0];
    sheet.setHiddenGridlines(true);

    const COLORS = { PRIMARY: '#4e54c8', BORDER: '#636e72', AI_BG: '#f3e5f5', AI_TEXT: '#4a148c', STRIPE: '#fcfcfc' };

    // Dynamic User Header Name Extraction
    const userNameForHeader = (employeeFilter && employeeFilter !== 'All Employees' && employeeFilter !== 'All') ? employeeFilter : requestingUser;
    const mainHeaderTitle = `${userNameForHeader.trim().toUpperCase()} EXPENSE REPORT`;

    sheet.getRange('A1:M1').merge().setValue(mainHeaderTitle).setFontFamily('Roboto').setFontSize(22).setFontWeight('bold').setFontColor(COLORS.PRIMARY);
    sheet.getRange('A2:M2').merge().setValue(`Generated By: ${requestingUser} | Filter: ${employeeFilter || 'All'}`).setFontFamily('Roboto').setFontSize(10).setFontColor('#636e72');
    sheet.getRange('A3:M3').merge().setValue(`Period: ${formatIsoToDisplayDate(fromDateStr)} — ${formatIsoToDisplayDate(toDateStr)}`).setFontFamily('Roboto').setFontSize(11).setFontWeight('bold');

    // Summary boxes anchored to columns N:P
    sheet.getRange('N1:P2').merge().setValue("GRAND TOTAL").setHorizontalAlignment('center').setVerticalAlignment('bottom').setFontSize(9).setFontColor('#636e72');
    sheet.getRange('N3:P4').merge().setValue(reportDataRes.totals.grandTotal).setNumberFormat('₹#,##0.00').setHorizontalAlignment('center').setVerticalAlignment('top').setFontSize(20).setFontWeight('bold').setFontColor(COLORS.PRIMARY);
    sheet.getRange('N1:P4').setBackground('#f8f9fa').setBorder(true, true, true, true, true, true, COLORS.BORDER, SpreadsheetApp.BorderStyle.SOLID);

    if (reportDataRes.insight && reportDataRes.insight.text) {
      sheet.getRange('N6:P6').merge().setValue("SMART INSIGHT").setFontSize(8).setFontColor(COLORS.AI_TEXT).setFontWeight('bold').setHorizontalAlignment('center');
      sheet.getRange('N7:P10').merge().setValue(reportDataRes.insight.text.replace(/<[^>]*>/g, '')).setFontSize(9).setFontColor(COLORS.AI_TEXT).setWrapStrategy(SpreadsheetApp.WrapStrategy.WRAP).setVerticalAlignment('top');
      sheet.getRange('N6:P10').setBackground(COLORS.AI_BG).setBorder(true, true, true, true, true, true, COLORS.AI_TEXT, SpreadsheetApp.BorderStyle.DOTTED);
    }

    // Exactly 16 Specific Columns
    const headers = [
        "Travel Day", "Name", "Customer Name", "Starting Point", "End Point",
        "Mode of Travel", "Location", "Travel Cost", "Fooding Cost",
        "Other Expense", "Equipment Transport", "Material Purchase",
        "GST Amount", "Remarks", "Bike KM", "Remarks if Other Expense"
    ];
    
    const startRow = 12;
    setupAutofitColumnWidths(sheet); 
    
    // Header Formatting: WRAP strategy is critically enforced here to prevent horizontal text clipping
    sheet.getRange(startRow, 1, 1, 16)
         .setValues([headers])
         .setBackground(COLORS.PRIMARY)
         .setFontColor('white')
         .setFontWeight('bold')
         .setFontSize(8) 
         .setHorizontalAlignment('center')
         .setVerticalAlignment('middle')
         .setWrapStrategy(SpreadsheetApp.WrapStrategy.WRAP) 
         .setBorder(true, true, true, true, true, true, 'black', SpreadsheetApp.BorderStyle.SOLID);
         
    // Allocate sufficient fixed height for wrapped header lines
    sheet.setRowHeight(startRow, 55);

    // Index mapping matching exactly the requested 16 sequences
    const pdfRows = data.map(row => {
      
      // Formatting Travel Day safely without utilizing timezone-vulnerable Date objects
      let displayTravelDay = row[3] ? String(row[3]) : '';
      if (displayTravelDay.match(/^\d{4}-\d{2}-\d{2}$/)) {
        const dateParts = displayTravelDay.split('-');
        displayTravelDay = `${dateParts[2]}-${dateParts[1]}-${dateParts[0]}`;
      }
      
      return [
        displayTravelDay, // Travel Day (DD-MM-YYYY)
        row[2] || '', // Name
        row[4] || '', // Customer Name
        row[5] || '', // Starting Point
        row[6] || '', // End Point
        row[7] || '', // Mode of Travel
        row[8] || '', // Location
        row[9] === 0 ? '0' : (row[9] || '0'), // Travel Cost
        row[10] === 0 ? '0' : (row[10] || '0'), // Fooding Cost
        row[11] === 0 ? '0' : (row[11] || '0'), // Other Expense
        row[12] === 0 ? '0' : (row[12] || '0'), // Equipment Transport
        row[13] === 0 ? '0' : (row[13] || '0'), // Material Purchase
        row[19] === 0 ? '0' : (row[19] || '0'), // GST Amount
        row[14] || '', // Remarks
        row[16] === 0 ? '0' : (row[16] || ''), // Bike KM
        row[15] || ''  // Remarks if Other Expense
      ];
    });

    // Data Rows Formatting
    sheet.getRange(startRow + 1, 1, pdfRows.length, 16)
         .setValues(pdfRows)
         .setFontFamily('Roboto')
         .setFontSize(8)
         .setVerticalAlignment('middle')
         .setWrapStrategy(SpreadsheetApp.WrapStrategy.WRAP)
         .setBorder(true, true, true, true, true, true, COLORS.BORDER, SpreadsheetApp.BorderStyle.SOLID);
    
    // Financial formatting covers Col 8 to 13
    sheet.getRange(startRow + 1, 8, pdfRows.length, 6).setNumberFormat('#,##0.00'); 
    
    for (let i = 0; i < pdfRows.length; i++) {
      if (i % 2 !== 0) sheet.getRange(startRow + 1 + i, 1, 1, 16).setBackground(COLORS.STRIPE);
      // NOTE: Fixed row height (sheet.setRowHeight) is purposefully OMITTED here. 
      // This allows Google Sheets to natively auto-expand the row height to perfectly fit long wrapped remarks.
    }

    addFooterRow(sheet, startRow + 1 + pdfRows.length, pdfRows);
    sheet.setFrozenRows(startRow);
    SpreadsheetApp.flush();

    // portrait=false dynamically enforces Landscape rendering
    const pdfFile = exportSpreadsheetToPdf(tempSS, sheet.getSheetId());
    return { success: true, name: pdfFile.getName(), url: pdfFile.getUrl() };

  } catch (error) { return { success: false, message: error.toString() }; } finally { if (tempSS) DriveApp.getFileById(tempSS.getId()).setTrashed(true); }
}

function exportSpreadsheetToPdf(ss, sheetId) {
  // portrait=false & fitw=true enforces A4 Landscape dynamically
  const url = ss.getUrl().replace(/\/edit.*$/, '') + '/export?format=pdf&size=a4&portrait=false&fitw=true&sheetnames=false&printtitle=false&gridlines=false&fzr=true' + (sheetId ? '&gid=' + sheetId : '');
  const response = UrlFetchApp.fetch(url, { headers: { 'Authorization': 'Bearer ' + ScriptApp.getOAuthToken() } });
  let folder; try { folder = DriveApp.getFolderById(PDF_FOLDER_ID); } catch(e) { folder = DriveApp.getRootFolder(); }
  return folder.createFile(response.getBlob().setName(`Enterprise_Report_${Date.now()}.pdf`));
}

function setupAutofitColumnWidths(sheet) {
  // Re-balanced width assignments accommodating A4 Landscape bounds perfectly for 16-cols
  sheet.setColumnWidth(1, 60);  // Travel Day
  sheet.setColumnWidth(2, 70);  // Name
  sheet.setColumnWidth(3, 75);  // Customer Name
  sheet.setColumnWidth(4, 65);  // Starting Point
  sheet.setColumnWidth(5, 65);  // End Point
  sheet.setColumnWidth(6, 55);  // Mode of Travel
  sheet.setColumnWidth(7, 60);  // Location
  sheet.setColumnWidth(8, 50);  // Travel Cost
  sheet.setColumnWidth(9, 50);  // Fooding Cost
  sheet.setColumnWidth(10, 55); // Other Expense
  sheet.setColumnWidth(11, 55); // Equipment Transport
  sheet.setColumnWidth(12, 55); // Material Purchase
  sheet.setColumnWidth(13, 50); // GST Amount
  sheet.setColumnWidth(14, 75); // Remarks
  sheet.setColumnWidth(15, 45); // Bike KM
  sheet.setColumnWidth(16, 75); // Remarks if Other Expense
}

function addFooterRow(sheet, rowIdx, data) {
  let subTotals = new Array(16).fill('');
  // Iterates the 6 specific financial columns
  data.forEach(row => { [7, 8, 9, 10, 11, 12].forEach(c => subTotals[c] = (subTotals[c] || 0) + (Number(row[c]) || 0)); });
  subTotals[0] = 'SUBTOTAL';
  
  sheet.getRange(rowIdx, 1, 1, 16)
       .setValues([subTotals])
       .setBackground('#e6e6e6')
       .setFontWeight('bold')
       .setFontSize(8)
       .setVerticalAlignment('middle')
       .setWrapStrategy(SpreadsheetApp.WrapStrategy.WRAP)
       .setBorder(true, true, true, true, true, true, 'black', SpreadsheetApp.BorderStyle.SOLID);
       
  // Merge the first two cells (Travel Day and Name) and retain right alignment
  sheet.getRange(rowIdx, 1, 1, 2).merge().setHorizontalAlignment('right');
       
  sheet.getRange(rowIdx, 8, 1, 6).setNumberFormat('₹#,##0.00');
}